"""Add(Fields): added state field in store table

Revision ID: 87c790507b64
Revises: d3085413454f
Create Date: 2023-12-23 14:55:52.387352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c790507b64'
down_revision: Union[str, None] = 'd3085413454f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'state')
    # ### end Alembic commands ###
