"""Add(Fields): added longtitude and latitude columns in store db

Revision ID: d3085413454f
Revises: 12c4620bd3fd
Create Date: 2023-12-23 13:43:43.010708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3085413454f'
down_revision: Union[str, None] = '12c4620bd3fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('longtitude', sa.Double(), nullable=True))
    op.add_column('stores', sa.Column('latitude', sa.Double(), nullable=True))
    op.drop_index('ix_stores_new_name', table_name='stores')
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.create_index(op.f('ix_stores_name'), 'stores', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stores_name'), table_name='stores')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.create_index('ix_stores_new_name', 'stores', ['name'], unique=False)
    op.drop_column('stores', 'latitude')
    op.drop_column('stores', 'longtitude')
    # ### end Alembic commands ###
